export const popularProducts = [{
        id: 1,
        img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
        title: "Printed T-Shirt",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "10.00",
        category: "tshirt",
    },
    {
        id: 2,
        img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
        title: "Long Jacket",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "70.00",
        category: "jackets",
    },
    {
        id: 3,
        img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
        title: "Hawaii Shirt",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "20",
        category: "shirts",
    },
    {
        id: 4,
        img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
        title: "White Women Dress",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "35",
        category: "dress",
    },
    {
        id: 5,
        img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
        title: "Leather Bag",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "100",
        category: "bags",
    },
    {
        id: 6,
        img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
        title: "Printed Cap",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "5",
        category: "caps",
    },
    {
        id: 7,
        img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
        title: "Hawaii Shirt",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "20",
        category: "shirts",
    },
    {
        id: 8,
        img: "https://www.pngall.com/wp-content/uploads/2016/07/Dress-PNG-File.png",
        title: "Red Women Dress",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "35",
        category: "dress",

    },
    {
        id: 9,
        img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
        title: "Round Neck T-Shirt",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "10",
        category: "tshirt",

    },
    {
        id: 10,
        img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
        title: "Long Women Jacket",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "70",
        category: "jackets",

    },
    {
        id: 11,
        img: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1614188818-TD1MTHU_SHOE_ANGLE_GLOBAL_MENS_TREE_DASHERS_THUNDER_b01b1013-cd8d-48e7-bed9-52db26515dc4.png?crop=1xw:1.00xh;center,top&resize=480%3A%2A",
        title: "Black Converse Shoes",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "100",
        category: "shoes",
    },
    {
        id: 12,
        img: "https://i.pinimg.com/originals/2d/af/f8/2daff8e0823e51dd752704a47d5b795c.png",
        title: "Round Neck T-Shirt",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, eum error dolor obcaecati accusamus nulla et aut perspiciatis alias iste, nesciunt ab. Velit excepturi temporibus similique exercitationem eveniet quo sint.Lorem exercitationem eveniet quo sint.",
        price: "10",
        category: "tshirt",

    },

];